title: Classroom Jukebox
description: "August 2023 to June 2024"
owner_name: Tirth Thakkar
github_username: aidenhuynh
github_repo: "cj_frontend"
baseurl: "/cj_frontend"
theme: jekyll-theme-yat
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/aidenhuynh"}
    - { platform: github, user_url: "https://github.com/Toby-Leeder"}
    - { platform: github, user_url: "https://github.com/Ryanrob327"}
    - { platform: github, user_url: "https://github.com/Ishi-Singh"}
    - { platform: github, user_url: "https://github.com/EdwinKuttappi"}
    - { platform: github, user_url: "https://github.com/firestorm0986"}
    - { platform: github, user_url: "https://github.com/KKcbal"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
